name: Django and React CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with: {python-version: "3.11"}
      - name: Install Django dependencies
        run: cd server && pip install -r requirements.txt
      - name: Migrate database
        run: cd server && python manage.py migrate
      - name: Django system checks
        run: cd server && python manage.py check
      - name: Set up Node
        uses: actions/setup-node@v4
        with: {node-version: "20"}
      - name: Build React
        run: cd frontend && npm install && npm run build
